import type { Config } from "jest";

const config: Config = {
  preset: "ts-jest/presets/default-esm",
  testEnvironment: "node",
  extensionsToTreatAsEsm: [".ts"],
  moduleFileExtensions: ["ts", "js", "json", "node"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/$1",
  },
  transform: {
    "^.+\\.[tj]sx?$": ["ts-jest", { useESM: true, tsconfig: "tsconfig.json" }],
  },
  resetMocks: true,
  restoreMocks: true,
  clearMocks: true,
  collectCoverage: true,
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html", "json-summary"],
  collectCoverageFrom: [
    "**/*.ts",
    "!**/*.d.ts",
    "!**/node_modules/**",
    "!**/*.test.ts",
    "!**/*.spec.ts",
    "!**/coverage/**",
    "!**/dist/**",
    "!**/__mocks__/**",
    "!app.ts",
    "!jest.config.ts",
    "!jest.setup.ts",
    "!database.types.ts",
    "!.taskmaster/**",
    "!routes/**",
    "!config/root-config.ts",
    "!ai-agents/agents.ts",
    "!ai-agents/agents-tools.ts",
    "!ai-agents/agents-instructions.ts",
    "!ai-agents/agents-hands-off-description.ts",
    "!ai-agents/description-tools.ts",
    "!ai-agents/parameters-tools.ts",
    "!telegram-bot/**",
    "!controllers/**",
    "!utils/activate-agent.ts",
    "!utils/get-tokens-user-ai.ts",
    "!utils/handle-events.ts",
    "!utils/init-calendar-with-user-tokens-and-update-tokens.ts",
    "!utils/update-calendar-categories.ts",
    "!utils/update-tokens-of-user.ts",
    "!utils/third-party-signup-signin-supabase.ts",
    "!ai-agents/execution-tools.ts",
    "!utils/get-user-calendar-tokens.ts",
  ],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
  testMatch: ["**/__tests__/**/*.test.ts", "**/?(*.)+(spec|test).ts"],
  setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],
};
export default config;
