export {
  type AgentProfile,
  type AgentTier,
  type AgentCapability,
  type VoiceStyle,
  AGENT_PROFILES,
  DEFAULT_AGENT_PROFILE_ID,
  getAgentProfile,
  getProfilesForTier,
  getRealtimeProfiles,
  type ModelProvider,
  type ModelTier,
  type ModelSpec,
  getModelSpec,
  getRealtimeModelId,
  isRealtimeSupported,
  type VoiceAgentConfig,
  type CreateVoiceAgentOptions,
  type AgentProfileResponse,
  createVoiceAgent,
  formatProfileForClient,
  type Modality as TextModality,
  type TextAgentConfig,
  type CreateTextAgentOptions,
  type StreamEvent,
  type RunTextAgentOptions,
  createTextAgent,
  runTextAgent,
  supportsTools,
} from "./orchestrator"

export {
  type MessageRole,
  type Message,
  type ToolCall,
  type ToolDefinition,
  type ChatParams,
  type ChatResponse,
  type StreamChunk,
  type LLMProvider,
  type ProviderConfig,
  createProviderFromProfile,
  isOpenAIProvider,
  createOpenAIProvider,
  createGoogleProvider,
  createAnthropicProvider,
} from "./llm"

export {
  unifiedContextStore,
  type Modality as ContextModality,
  type EventReference,
  type CalendarReference,
  type ConversationContext,
  type UserPreferencesContext,
  type ContextSnapshot,
  entityTracker,
  type TrackedEvent,
  type TrackedCalendar,
} from "./context"

export {
  CORE_IDENTITY,
  CORE_CAPABILITIES,
  CORE_BEHAVIOR,
  AUTH_CONTEXT,
  INTENT_RECOGNITION,
  TIME_INFERENCE,
  ERROR_HANDLING,
  RESPONSE_STYLE,
  buildBasePrompt,
  buildOrchestratorPrompt,
} from "./prompts"

export {
  type HandlerContext,
  getEventHandler,
  insertEventHandler,
  updateEventHandler,
  deleteEventHandler,
  validateUserHandler,
  getTimezoneHandler,
  selectCalendarHandler,
  checkConflictsHandler,
  preCreateValidationHandler,
  type ValidateUserResult,
  type TimezoneResult,
  type SelectCalendarResult,
  type ConflictCheckResult,
  type PreCreateValidationResult,
  analyzeGapsHandler,
  fillGapHandler,
  formatGapsHandler,
  type GapCandidateDTO,
  type AnalyzeGapsResult,
  type FillGapResult,
  type FormatGapsResult,
} from "./tools/handlers"

export {
  type ToolExecutorContext,
  type ToolExecutionResult,
  executeTool,
  executeTools,
  getAvailableToolNames,
  isToolAvailable,
} from "./tools/tool-executor"
