export {
  type CalendarReference,
  type ContextSnapshot,
  type ConversationContext,
  type EventReference,
  entityTracker,
  type Modality as ContextModality,
  type TrackedCalendar,
  type TrackedEvent,
  type UserPreferencesContext,
  unifiedContextStore,
} from "./context";

export {
  type ChatParams,
  type ChatResponse,
  createAnthropicProvider,
  createGoogleProvider,
  createOpenAIProvider,
  createProviderFromProfile,
  isOpenAIProvider,
  type LLMProvider,
  type Message,
  type MessageRole,
  type ProviderConfig,
  type StreamChunk,
  type ToolCall,
  type ToolDefinition,
} from "./llm";
export {
  AGENT_PROFILES,
  type AgentCapability,
  type AgentProfile,
  type AgentProfileResponse,
  type AgentTier,
  type CreateTextAgentOptions,
  createTextAgent,
  DEFAULT_AGENT_PROFILE_ID,
  formatProfileForClient,
  getAgentProfile,
  getModelSpec,
  getProfilesForTier,
  type Modality as TextModality,
  type ModelProvider,
  type ModelSpec,
  type ModelTier,
  type RunTextAgentOptions,
  runTextAgent,
  type StreamEvent,
  supportsTools,
  type TextAgentConfig,
  type VoiceStyle,
} from "./orchestrator";

export {
  AUTH_CONTEXT,
  buildBasePrompt,
  buildOrchestratorPrompt,
  CORE_BEHAVIOR,
  CORE_CAPABILITIES,
  CORE_IDENTITY,
  ERROR_HANDLING,
  INTENT_RECOGNITION,
  RESPONSE_STYLE,
  TIME_INFERENCE,
} from "./prompts";

export {
  type AnalyzeGapsResult,
  analyzeGapsHandler,
  type ConflictCheckResult,
  checkConflictsHandler,
  deleteEventHandler,
  type FillGapResult,
  type FormatGapsResult,
  fillGapHandler,
  formatGapsHandler,
  type GapCandidateDTO,
  getCalendarCategoriesByEmail,
  getEventHandler,
  getTimezoneHandler,
  type HandlerContext,
  insertEventHandler,
  type PreCreateValidationResult,
  preCreateValidationHandler,
  type SelectCalendarResult,
  selectCalendarHandler,
  type TimezoneResult,
  type UserCalendar,
  updateEventHandler,
  type ValidateUserResult,
  validateUserHandler,
} from "./tools/handlers";

export {
  executeTool,
  executeTools,
  getAvailableToolNames,
  isToolAvailable,
  type ToolExecutionResult,
  type ToolExecutorContext,
} from "./tools/tool-executor";

export {
  type AgentContext as SharedAgentContext,
  type ConflictCheckResult as SharedConflictCheckResult,
  type ConflictingEvent,
  categorizeError,
  type HandlerContext as SharedHandlerContext,
  type Modality,
  type ProjectionMode,
  stringifyError,
} from "./types";
