export { FeatureShowcase, default } from './FeatureShowcase'
export type { Platform, Message, Feature } from './types'
export { FEATURES } from './data/features'

export { TypingIndicator } from './components/TypingIndicator'
export { VoiceWaveform } from './components/VoiceWaveform'
export { PhoneMockup } from './components/PhoneMockup'
export { BrowserMockup } from './components/BrowserMockup'
export { PlatformToggle } from './components/PlatformToggle'
export { TelegramChat } from './components/TelegramChat'
export { SlackChat } from './components/SlackChat'
export { WhatsAppChat } from './components/WhatsAppChat'

export { WebCalendarView } from './views/WebCalendarView'
export { WebAnalyticsView } from './views/WebAnalyticsView'
export { WebChatView } from './views/WebChatView'
export { WebBrainView } from './views/WebBrainView'
