import type { MetadataRoute } from 'next'
import { SITE_CONFIG } from '@/lib/constants/seo'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/dashboard/',
          '/admin/',
          '/callback/',
          '/auth/',
          '/loading/',
          '/shared/',
          '/onboarding/',
          '/data-deletion-status/',
          '/integrations/',
        ],
      },
      {
        userAgent: 'GPTBot',
        allow: '/',
        disallow: [
          '/api/',
          '/dashboard/',
          '/admin/',
          '/callback/',
          '/auth/',
          '/loading/',
          '/shared/',
          '/onboarding/',
          '/data-deletion-status/',
          '/integrations/',
        ],
      },
      {
        userAgent: 'ChatGPT-User',
        allow: '/',
        disallow: [
          '/api/',
          '/dashboard/',
          '/admin/',
          '/callback/',
          '/auth/',
          '/loading/',
          '/shared/',
          '/onboarding/',
          '/data-deletion-status/',
          '/integrations/',
        ],
      },
      {
        userAgent: 'Google-Extended',
        allow: '/',
        disallow: [
          '/api/',
          '/dashboard/',
          '/admin/',
          '/callback/',
          '/auth/',
          '/loading/',
          '/shared/',
          '/onboarding/',
          '/data-deletion-status/',
          '/integrations/',
        ],
      },
      {
        userAgent: 'Anthropic-AI',
        allow: '/',
        disallow: [
          '/api/',
          '/dashboard/',
          '/admin/',
          '/callback/',
          '/auth/',
          '/loading/',
          '/shared/',
          '/onboarding/',
          '/data-deletion-status/',
          '/integrations/',
        ],
      },
      {
        userAgent: 'Claude-Web',
        allow: '/',
        disallow: [
          '/api/',
          '/dashboard/',
          '/admin/',
          '/callback/',
          '/auth/',
          '/loading/',
          '/shared/',
          '/onboarding/',
          '/data-deletion-status/',
          '/integrations/',
        ],
      },
    ],
    sitemap: `${SITE_CONFIG.url}/sitemap.xml`,
  }
}
