AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Daily Briefing Email System - AWS EventBridge + Lambda + SQS

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]
  SupabaseUrl:
    Type: String
    Description: Supabase project URL
  SupabaseServiceKey:
    Type: String
    Description: Supabase service role key
    NoEcho: true
  ResendApiKey:
    Type: String
    Description: Resend API key for sending emails
    NoEcho: true
  ResendFromEmail:
    Type: String
    Default: "Ally <ally@ally.sh>"
    Description: Email address to send from
  GoogleClientId:
    Type: String
    Description: Google OAuth client ID
  GoogleClientSecret:
    Type: String
    Description: Google OAuth client secret
    NoEcho: true
  AppUrl:
    Type: String
    Default: "https://ally.sh"
    Description: Application URL for email links

Globals:
  Function:
    Runtime: nodejs20.x
    MemorySize: 256
    Timeout: 60
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        SUPABASE_URL: !Ref SupabaseUrl
        SUPABASE_SERVICE_ROLE_KEY: !Ref SupabaseServiceKey
        RESEND_API_KEY: !Ref ResendApiKey
        RESEND_FROM_EMAIL: !Ref ResendFromEmail
        GOOGLE_CLIENT_ID: !Ref GoogleClientId
        GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
        APP_URL: !Ref AppUrl

Resources:
  # SQS Queue for email jobs
  BriefingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub daily-briefing-queue-${Environment}.fifo
      FifoQueue: true
      ContentBasedDeduplication: false
      VisibilityTimeout: 300
      MessageRetentionPeriod: 345600  # 4 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt BriefingDLQ.Arn
        maxReceiveCount: 3

  # Dead Letter Queue for failed messages
  BriefingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub daily-briefing-dlq-${Environment}.fifo
      FifoQueue: true
      MessageRetentionPeriod: 1209600  # 14 days

  # Scheduler Lambda - queries users and sends to SQS
  SchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub daily-briefing-scheduler-${Environment}
      Handler: scheduler.handler
      CodeUri: ./src
      MemorySize: 256
      Timeout: 60
      Environment:
        Variables:
          QUEUE_URL: !Ref BriefingQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt BriefingQueue.QueueName
      Events:
        ScheduleRule:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Name: !Sub daily-briefing-schedule-${Environment}
            Enabled: true
            Description: Trigger daily briefing scheduler every 5 minutes

  # Email Sender Lambda - processes SQS and sends emails
  EmailSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub daily-briefing-sender-${Environment}
      Handler: sender.handler
      CodeUri: ./src
      MemorySize: 512
      Timeout: 300
      ReservedConcurrentExecutions: 5
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt BriefingQueue.Arn
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures

  # CloudWatch Alarm for DLQ messages
  DLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub daily-briefing-dlq-alarm-${Environment}
      AlarmDescription: Alarm when messages appear in the dead letter queue
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt BriefingDLQ.QueueName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

  # CloudWatch Log Groups
  SchedulerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/daily-briefing-scheduler-${Environment}
      RetentionInDays: 14

  SenderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/daily-briefing-sender-${Environment}
      RetentionInDays: 14

Outputs:
  QueueUrl:
    Description: URL of the SQS queue
    Value: !Ref BriefingQueue
  QueueArn:
    Description: ARN of the SQS queue
    Value: !GetAtt BriefingQueue.Arn
  DLQUrl:
    Description: URL of the dead letter queue
    Value: !Ref BriefingDLQ
  SchedulerFunctionArn:
    Description: ARN of the scheduler function
    Value: !GetAtt SchedulerFunction.Arn
  EmailSenderFunctionArn:
    Description: ARN of the email sender function
    Value: !GetAtt EmailSenderFunction.Arn
