/**
 * Generated API types
 * 
 * This file is auto-generated by the generate-types script.
 * DO NOT EDIT THIS FILE MANUALLY.
 * 
 * To regenerate types, run: npm run generate:types
 */

// This file will be generated by the type generation script
// Placeholder until types are generated
export type GeneratedApiTypes = Record<string, never>;
