import type { Config } from "jest";

const config: Config = {
  preset: "ts-jest/presets/default-esm",
  testEnvironment: "node",
  extensionsToTreatAsEsm: [".ts"],
  moduleFileExtensions: ["ts", "js", "json", "node"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/$1",
  },
  transform: {
    "^.+\\.[tj]sx?$": ["ts-jest", { useESM: true, tsconfig: "tsconfig.json" }],
  },
  resetMocks: true,
  restoreMocks: true,
  clearMocks: true,
  collectCoverage: true,
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html", "json-summary"],
  collectCoverageFrom: [
    "**/*.ts",
    "!**/*.d.ts",
    "!**/node_modules/**",
    "!**/*.test.ts",
    "!**/*.spec.ts",
    "!**/coverage/**",
    "!**/dist/**",
    "!**/mocks/**",
    "!**/tests/**",
    "!app.ts",
    "!jest.config.ts",
    "!jest.setup.ts",
    "!database.types.ts",
    "!.taskmaster/**",
    "!routes/**",
    "!config/root-config.ts",
    "!telegram-bot/**",
    "!controllers/**",
    "!utils/**",
    "!ai-agents/**",
  ],
  coverageThreshold: {
    global: {
      branches: 75,
      functions: 75,
      lines: 75,
      statements: 75,
    },
    "./tests/domain/**/*.ts": {
      branches: 95,
      functions: 95,
      lines: 95,
      statements: 95,
    },
    "./tests/application/**/*.ts": {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
    "./tests/infrastructure/**/*.ts": {
      branches: 75,
      functions: 75,
      lines: 75,
      statements: 75,
    },
    "./tests/controller/**/*.ts": {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  testMatch: ["**/tests/**/*.test.ts", "**/?(*.)+(spec|test).ts"],
  setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],
};
export default config;
