#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run Biome lint, continue even if errors
echo "Running Biome lint..."
biome lint . --fix || true

# Run Biome format, continue even if it changes files
echo "Running Biome format..."
biome format . --write || true
